//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanaraha.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
          //  this.ItemLinks = new HashSet<ItemLink>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int TopicId { get; set; }
        public string MainUrl { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    
        //public virtual ICollection<ItemLink> ItemLinks { get; set; }
        public virtual Topic Topic { get; set; }
    }
}
